apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-code-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch-code-app
  template:
    metadata:
      labels:
        app: ch-code-app
    spec:
      containers:
      - name: ch-code-app
        image: ch-code-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
        env:
        - name: CUSTOM_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: ch-config
              key: custom_message